name: C/C++ CI

on:
  push:
    branches: [ main-nightly ]
  pull_request:
    branches: [ main-nightly ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: |
          ThirdTube.3dsx
          ThirdTube.cia
